[tool.poetry]
name = "new-year-bell"
version = "0.1.0"
description = ""
authors = ["dskim6797 <dskim6797@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "5.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
